name = "openclash-subscription"
main = "src/worker.js"
compatibility_date = "2023-12-01"

[triggers]
crons = ["0 */4 * * *"] # 每4小时执行一次

[[kv_namespaces]]
binding = "OPENCLASH_KV"
id = "0d2d44181978408ca3ca05e0e9b8306c"
