name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */24 * * *' # 每24小时部署一次

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Volta (Node.js 20)
        uses: volta-cli/action@v4
        with:
          node-version: 20

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: wrangler publish
